export const initData = [
    {
        "id" : 0,
        "parentId" : -1,
        "name" : "此电脑",
        "path" : "/",
        "recent" : 0,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 1,
        "parentId" : 0,
        "name" : "C:",
        "path" : "/C/",
        "recent" : 1,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 2,
        "parentId" : 0,
        "name" : "D:",
        "path" : "/D/",
        "recent" : 1,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 3,
        "parentId" : 0,
        "name" : "回收站",
        "path" : "/B/",
        "recent" : 1,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 5,
        "parentId" : 1,
        "name" : "用户",
        "path" : "/C/Users",
        "recent" : 1,
        "ext" : "",
        "icon": "user",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 11,
        "parentId" : 5,
        "name" : "桌面",
        "path" : "/C/Users/Desktop",
        "recent" : 0,
        "ext" : "",
        "icon": "desk",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 12,
        "parentId" : 5,
        "name" : "文档",
        "path" : "/C/Users/Documents",
        "recent" : 1,
        "ext" : "",
        "icon": "docs",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 13,
        "parentId" : 5,
        "name" : "图片",
        "path" : "/C/Users/Pictures",
        "recent" : 1,
        "ext" : "",
        "icon": "pics",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 14,
        "parentId" : 5,
        "name" : "音乐",
        "path" : "/C/Users/Music",
        "recent" : 1,
        "ext" : "",
        "icon": "music",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 15,
        "parentId" : 5,
        "name" : "视频",
        "path" : "/C/Users/Videos",
        "recent" : 1,
        "ext" : "",
        "icon": "vid",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 16,
        "parentId" : 5,
        "name" : "下载",
        "path" : "/C/Users/Downloads",
        "recent" : 1,
        "ext" : "",
        "icon": "down",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 30,
        "parentId" : 1,
        "name" : "系统",
        "recent" : 0,
        "path" : "/C/System",
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 31,
        "parentId" : 30,
        "name" : "应用程序",
        "path" : "/C/System/app",
        "recent" : 0,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 32,
        "parentId" : 30,
        "name" : "任务栏",
        "path" : "/C/System/taskbar",
        "recent" : 0,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 33,
        "parentId" : 30,
        "name" : "固钉",
        "path" : "/C/System/pinned",
        "recent" : 0,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 34,
        "parentId" : 30,
        "name" : "推荐",
        "path" : "/C/System/recent",
        "recent" : 0,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 35,
        "parentId" : 30,
        "name" : "动作",
        "path" : "/C/System/action",
        "recent" : 0,
        "ext" : "",
        "icon": "folder",
        "type" : "folder",
        "content" : ""
    },
    {
        "id" : 48,
        "parentId" : 35,
        "name": "Start",
        "path" : "/C/System/action/start.act",
        "recent" : 0,
        "ext" : "act",
        "icon": "home",
        "type": "action",
        "action": "STARTMENU",
        "content" : ""
      },
      {
        "id" : 49,
        "parentId" : 35,
        "name": "Search",
        "path" : "/C/System/action/search.act",
        "recent" : 0,
        "ext" : "act",
        "icon": "search",
        "type": "action",
        "action": "SEARCHMENU",
        "content" : ""
      },
      {
        "id" : 50,
        "parentId" : 35,
        "name": "Widget",
        "path" : "/C/System/action/widget.act",
        "recent" : 0,
        "ext" : "act",
        "icon": "widget",
        "type": "action",
        "action": "WIDGETS",
        "content" : ""
      },
    {
        "id" : 51,
        "parentId" : 31,
        "name" : "任务管理器",
        "path" : "/C/System/app/taskmanager.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "taskmanager",
        "type" : "app",
        "action": "TASKMANAGER",
        "content" : ""
    },
    {
        "id" : 52,
        "parentId" : 31,
        "name" : "文件管理器",
        "path" : "/C/System/app/explorer.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "explorer",
        "type" : "app",
        "action": "EXPLORER",
        "content" : 1
    },
    
    {
        "id" : 53,
        "parentId" : 31,
        "name" : "浏览器",
        "path" : "/C/System/app/edge.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "edge",
        "type" : "app",
        "action": "MSEDGE",
        "content" : ""
    },
    {
        "id" : 54,
        "parentId" : 31,
        "name" : "应用商店",
        "path" : "/C/System/app/store.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "store",
        "type" : "app",
        "action": "WNSTORE",
        "content" : ""
    },
    {
        "id" : 55,
        "parentId" : 31,
        "name" : "终端",
        "path" : "/C/System/app/terminal.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "terminal",
        "type" : "app",
        "action": "TERMINAL",
        "content" : ""
    },
    {
        "id" : 65,
        "parentId" : 31,
        "name" : "设置",
        "path" : "/C/System/app/settings.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "settings",
        "type" : "app",
        "action": "SETTINGS",
        "content" : ""
    },
    {
        "id" : 66,
        "parentId" : 31,
        "name" : "计算器",
        "path" : "/C/System/app/calculator.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "calculator",
        "type" : "app",
        "action": "CALCUAPP",
        "content" : ""
    },
    {
        "id" : 67,
        "parentId" : 31,
        "name" : "相机",
        "path" : "/C/System/app/camera.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "camera",
        "type" : "app",
        "action": "CAMERA",
        "content" : ""
    },
    {
        "id" : 68,
        "parentId" : 31,
        "name" : "涂鸦",
        "path" : "/C/System/app/board.exe",
        "recent" : 0,
        "ext" : "exe",
        "icon": "board",
        "type" : "app",
        "action": "WHITEBOARD",
        "content" : ""
    },
    {
        "id" : 101,
        "parentId" : 11,
        "name" : "此电脑",
        "path" : "/C/Users/Desktop/explorer.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "win/user",
        "type" : "app",
        "action": "EXPLORER",
        "content" : 0
    },
    {
        "id" : 102,
        "parentId" : 11,
        "name" : "浏览器",
        "path" : "/C/Users/Desktop/edge.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "edge",
        "type" : "app",
        "action": "MSEDGE",
        "content" : ""
    },
    {
        "id" : 103,
        "parentId" : 11,
        "name" : "回收站",
        "path" : "/C/Users/Desktop/bin0.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "bin0",
        "type" : "app",
        "action": "EXPLORER",
        "content" : 3
    },
    {
        "id" : 104,
        "parentId" : 11,
        "name" : "应用商店",
        "path" : "/C/Users/Desktop/store.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "store",
        "type" : "app",
        "action": "WNSTORE",
        "content" : ""
    },
    {
        "id" : 105,
        "parentId" : 11,
        "name" : "终端",
        "path" : "/C/System/taskbar/terminal.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "terminal",
        "type" : "app",
        "action": "TERMINAL",
        "content" : ""
    },
    {
        "id" : 121,
        "parentId" : 32,
        "name" : "设置",
        "path" : "/C/System/taskbar/settings.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "settings",
        "type" : "app",
        "action": "SETTINGS",
        "content" : 65
    },
    {
        "id" : 131,
        "parentId" : 34,
        "name" : "终端",
        "path" : "/C/System/recent/terminal.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "terminal",
        "type" : "app",
        "action": "TERMINAL",
        "content" : ""
    },
    {
        "id" : 132,
        "parentId" : 34,
        "name" : "任务管理器",
        "path" : "/C/System/recent/taskmanager.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "taskmanager",
        "type" : "app",
        "action": "TASKMANAGER",
        "content" : ""
    },

    {
        "id" : 201,
        "parentId" : 33,
        "name" : "计算器",
        "path" : "/C/System/pinned/calculator.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "calculator",
        "type" : "app",
        "action": "CALCUAPP",
        "content" : ""
    },
    {
        "id" : 202,
        "parentId" : 33,
        "name" : "相机",
        "path" : "/C/System/pinned/camera.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "camera",
        "type" : "app",
        "action": "CAMERA",
        "content" : ""
    },
    {
        "id" : 203,
        "parentId" : 31,
        "name" : "涂鸦",
        "path" : "/C/System/pinned/board.ln",
        "recent" : 0,
        "ext" : "ln",
        "icon": "board",
        "type" : "app",
        "action": "WHITEBOARD",
        "content" : ""
    },

]